session_name: randbeacon
windows:
    - window_name: proxy
      panes:
        - shell_command:
            - proxy/proxy stream "tcp://*:3333" "tcp://*:4444" "tcp://*:3344" &
            - pipenv run python3 proxy/snooper.py tcp://localhost:3344
        - shell_command:
            - proxy/proxy forward "tcp://*:5555" "tcp://*:6666" "tcp://*:5566" &
            - pipenv run python3 proxy/snooper.py tcp://localhost:5566
    - window_name: input stuff
      panes:
        - shell_command: pipenv run python3 -m randbeacon.input_collection.urandom --push-connect tcp://localhost:3333
        - shell_command: pipenv run python3 -m randbeacon.input_collection.simple_http --push-connect tcp://localhost:3333
        - shell_command: pipenv run python3 -m randbeacon.input_collection.simple_tcp --push-connect tcp://localhost:3333
      # panes:
      #   - shell_command: pipenv run python3 -m randbeacon.input_collection.spamming --push-connect tcp://localhost:3333 --spam-interval 2 --random
      layout: even-vertical
    - window_name: middle stuff
      panes:
        - shell_command: pipenv run python3 -m randbeacon.input_processing.merkle --pull-type connect --pull-addr tcp://localhost:4444
        - shell_command: pipenv run python3 -m randbeacon.computation.delay_sloth --pub-type connect --pub-addr tcp://localhost:5555
        - shell_command: pipenv run python3 -m randbeacon.computation.delay_sloth --pub-type connect --pub-addr tcp://localhost:5555
      layout: main-vertical
    - window_name: publish stuff
      panes:
        - shell_command: pipenv run python3 proxy/snooper.py tcp://localhost:6666
        - shell_command: pipenv run python3 -m randbeacon.publishing.json_dump --sub-connect tcp://localhost:6666 --json-output-dir output_json
